### ISSUE TITLE
InsertKoinIO/koin

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#10]
## About the library

- *Description*:    Koin - a pragmatic lightweight dependency injection framework for Kotlin 
- *GitHub*: https://github.com/InsertKoinIO/koin
- *Official website*: https://insert-koin.io/

## What the sample could do

Definitely **not** the meaningless example of the fancy coffee machine with a thermosiphon.

See the [Kodein-DI sample](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/kotlin-jvm/src/main/kotlin/playground/KodeinDI.kt)

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by douglascamata** [comment]
I can follow up with this one too. :D

**Comment by jmfayard** [comment]
go and go!

**Comment by jmfayard** [comment]
@douglascamata 
When you contribute it, please move all DI library samples under the package `playground.di`
https://github.com/LouisCAD/kotlin-libraries-playground/issues/29
