### ISSUE TITLE
Sample wanted for  Kodein-Framework/Kodein-DI 

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#11]
## About the library

- *Description*:    Painless Kotlin Dependency Injection 
- *GitHub*: https://github.com/Kodein-Framework/Kodein-DI
- *Official website*: https://kodein.org/di/

## What the sample could do

Definitely **not** the meaningless example of the fancy coffee machine with a thermosiphon.

Try to find something simple you could use in the real world. 

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by douglascamata** [comment]
Hi @jmfayard, I would like to work on this 💪

**Comment by LouisCAD** [comment]
Alright @douglascamata, let's go! 👌
