### ISSUE TITLE
Sample wanted for square/kotlinpoet

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#14]
## About the library

- *Description*:   `KotlinPoet` is a Kotlin and Java API for generating `.kt` source files.
- *GitHub*: https://github.com/square/kotlinpoet
- *API and documentation*: https://square.github.io/kotlinpoet/1.x/kotlinpoet/
- [Change Log](https://square.github.io/kotlinpoet/changelog/)

## What the sample could do

Up to you

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by dector** [comment]
Would love to get this

**Comment by LouisCAD** [comment]
Alright, go for it!
