### ISSUE TITLE
Sample wanted for JakeWharton/picnic

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#15]
## About the library

- *Description*:   A Kotlin DSL and Java/Kotlin builder API for constructing HTML-like tables which can be rendered to text.
- *GitHub*: [JakeWharton/picnic](https://github.com/JakeWharton/picnic)

## What the sample could do

Print a HTML-like table to the console :)

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by katerine-sg** [comment]
I want  to try to  do this one.

**Comment by jmfayard** [comment]
Go for it, it's assigned to you!
