### ISSUE TITLE
Sample wanted for apollographql/apollo-android

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#16]
## About the library

- *Description*:    🤖 A strongly-typed, caching GraphQL client for the JVM, Android and Kotlin multiplatform 
- *GitHub*: https://github.com/apollographql/apollo-android
- *Official website*: 

## What the sample could do

Use the sample from the Apollo tutorial

```
query LaunchList {
  launches {
    cursor
    hasMore
  }
}
```

https://www.apollographql.com/docs/tutorial/introduction/
https://apollo-fullstack-tutorial.herokuapp.com/

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by oppongjr** [comment]
@jmfayard can you assign this to me?

**Comment by jmfayard** [comment]
Sure thing!

**Comment by jmfayard** [comment]
Done

**Comment by oppongjr** [comment]
😭

**Comment by martinbonnin** [comment]
Oh my! Very sorry I missed that... I hope it matched what you had in mind @oppongjr, do not hesitate to modify if needed.

**Comment by LouisCAD** [comment]
@oppongjr Also, if you have ideas to improve it, show another use case or anything, feel free to let us know or show us a draft PR!

**Comment by oppongjr** [comment]
@LouisCAD Alright man.
