### ISSUE TITLE
Sample wanted for ajalt/mordant

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#18]
## About the library

- *Description*:    Full-featured text styling for Kotlin command-line applications 
- *GitHub*: https://github.com/ajalt/mordant

## What the sample could do

Print something nice to the console with colors and styles

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by DarthBenro008** [comment]
I would like to work on this !

**Comment by jmfayard** [comment]
Go for it!
