### ISSUE TITLE
Sample wanted for ajalt/clikt

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#19]
## About the library

- *Description*:    Multiplatform command line interface parsing for Kotlin 
- *GitHub*: https://github.com/ajalt/clikt
- *Official website*: https://ajalt.github.io/clikt/

## What the sample could do

Parse `myKotlinCli --language FR --greeting Bonjour`

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by mrclsu** [comment]
I'd love to give this a shot. 🚀

**Comment by jmfayard** [comment]
Thanks, go for it!
