### ISSUE TITLE
Sample wanted for thomasnield/kotlin-statistics

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#20]
## About the library

- *Description*:    Idiomatic statistical operators for Kotlin 
- *GitHub*: https://github.com/thomasnield/kotlin-statistics

## What the sample could do

Cool statistics in Kotlin

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by dector** [comment]
Can add some samples. :)

Also I want to add some visual illustrations. Can I create companion doc somewhere in the repo? What do you think?

**Comment by jmfayard** [comment]
@dector Sure, add a `docs` folder and put your Markdown or Asciidoc there
To upload images, the way I would do it is that I would upload the pictures to this issue,
and them simply use the image URL in the markdown file

**Comment by jmfayard** [comment]
> Also I want to add some visual illustrations. Can I create companion doc somewhere in the repo?

I've thought about it again. While of course you can add doc in this repo,
it could be even better if you write down a blog article externally.
If you don't have a personal blog yet, I can highly recommend DEV,
this is where I put my blog posts: https://dev.to/jmfayard/

**Comment by dector** [comment]
Okay, will try to avoid additional documentation. I guess you are right and the goal of this sample is not to explain statistics to reader so I can assume that one is familiar with basics a bit.

**Comment by jmfayard** [comment]
Hello @dector How is it going? Are you blocked somewhere?

**Comment by dector** [comment]
Sorry, no blockers. Just didn't want to publish unfinished implementation. Will update it and publish it in the next 24 hours.

**Comment by dector** [comment]
Okay, polished current implementation and creating PR - I guess simple working example is better than detailed but non-existent. 😄
