### ISSUE TITLE
Add a reliable style checker matching Kotlin official style guide that runs on commit or on GitHub Actions

### ISSUE THREAD

**Issue by LouisCAD** [LouisCAD/kotlin-libraries-playground#27]

**Comment by jmfayard** [comment]
put `kotlin.code.style=official` in `gradle.properties` https://dev.to/jmfayard/configuring-gradle-with-gradle-properties-211k

and add a section in the CONTRIBUTING guide?

**Comment by jmfayard** [comment]
I've added `kotlin.code.style=official` in gradle.properties

**Comment by LouisCAD** [comment]
Yes, a section about reformatting before submitting in the CONTRIBUTING.md would be great.

**Comment by jmfayard** [comment]
Done in https://github.com/LouisCAD/kotlin-libraries-playground/commit/9499cb0c2729c543c0a4a7e80999b972cb30d266
