### ISSUE TITLE
Sample wanted for cashapp/sqldelight 

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#3]
## About the library

- *Description*:  SQLDelight - Generates typesafe Kotlin APIs from SQL 
- *GitHub*: https://github.com/cashapp/sqldelight
- *Official website*: https://cashapp.github.io/sqldelight/

## What the sample could do

Two tables `User` and  `Order`. Show how to create the database, insert entries, do a relational query and delete entries

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by Sharkaboi** [comment]
Hey @jmfayard 
I'd like to have a take at this. Been wanting to try out SQLDelight aswell !
Also, How should I structure the packages to keep the `.sq` file for the database grouped neatly?

**Comment by jmfayard** [comment]
Go for it Sharkaboi!

For the folder structure, do whatever you think makes most sense
