### ISSUE TITLE
Sample wanted for Kotlin/kotlinx-datetime

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#32]
## About the library

- *Description*:    KotlinX multiplatform date/time library 
- *GitHub*: https://github.com/Kotlin/kotlinx-datetime

## What the sample could do

Show how to use `Instant`, `Clock`, `LocalDateTime`, `LocalDate`, Unix timestamp and how to convert from one to another

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by dector** [comment]
Can do it

**Comment by jmfayard** [comment]
Thanks!

**Comment by jmfayard** [comment]
Done in #37
