### ISSUE TITLE
Sample wanted for serpro69/kotlin-faker

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#33]
## About the library

- *Description*:  Port of a popular ruby faker gem written in Kotlin. 
- *GitHub*: https://github.com/serpro69/kotlin-faker

## What the sample could do

Generate random User, Address, Friends, Phoe number, Rick and Morty

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by larissayasin** [comment]
I can do it!

**Comment by jmfayard** [comment]
Thanks larissa!

**Comment by larissayasin** [comment]
@jmfayard I'm following the instructions and  but I'm having some problems..
I added the` implementation("com.github.moove-it:fakeit:_")` and also added inside `repositories {  maven(url = "https://jitpack.io") ...` but I when I try to import `import com.mooveit.library.Fakeit` I get an _Unresolved reference error._ 

I tried to use the Fakeit lib in another project but I'm I can't initialize it. There is a issue about it [#62](https://github.com/moove-it/fakeit/issues/62)

I was looking for solutions and I found this library as an alternative: https://github.com/serpro69/kotlin-faker 
What do you think about using Kotlin-Faker instead?

**Comment by jmfayard** [comment]
done in  #39
