### ISSUE TITLE
Sample wanted for MarkusAmshove/Kluent

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#35]
## About the library

- *Description*:    Fluent Assertion-Library for Kotlin 
- *GitHub*: https://github.com/MarkusAmshove/Kluent
- *Official website*: https://markusamshove.github.io/Kluent/

## What the sample could do

Add kluent examples in `src/test`, maybe follow what was done for `strikt`
https://github.com/LouisCAD/kotlin-libraries-playground/tree/main/kotlin-jvm/src/test/kotlin/framework
See also Atrium https://github.com/LouisCAD/kotlin-libraries-playground/issues/36

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by fejd** [comment]
I'd like to work on this issue.

**Comment by jmfayard** [comment]
Go for it!  @fejd

**Comment by jmfayard** [comment]
Hello @fejd ! How is it going? Are you blocked somewhere?

**Comment by fejd** [comment]
@jmfayard Sorry, I had a patch almost done but got distracted! I'll upload it today or tomorrow evening!
