### ISSUE TITLE
Sample wanted for robstoll/atrium

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#36]
## About the library

- *Description*:    A multiplatform assertion library for Kotlin 
- *GitHub*: https://github.com/robstoll/atrium
- *Official website*: https://docs.atriumlib.org/

## What the sample could do

Add kluent examples in src/test, maybe follow what was done for strikt
https://github.com/LouisCAD/kotlin-libraries-playground/tree/main/kotlin-jvm/src/test/kotlin/framework
See also kluent https://github.com/LouisCAD/kotlin-libraries-playground/issues/35

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by oppongjr** [comment]
@jmfayard Please assign this to me
