### ISSUE TITLE
Sample wanted for Kotlin/kotlinx.html

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#4]
## About the library

- *Description*:   Kotlin DSL for HTML
- *GitHub*: https://github.com/Kotlin/kotlinx.html
- *Official website*: https://github.com/Kotlin/kotlinx.html

## What the sample could do

Generate the HTML for an email

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by dector** [comment]
Would love to contribute with this :)

**Comment by LouisCAD** [comment]
@dector Do it! 😃
