### ISSUE TITLE
Sample wanted for ReactiveX/RxJava

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#41]
## About the library

- *Description*:    RxJava – Reactive Extensions for the JVM – a library for composing asynchronous and event-based programs using observable sequences for the Java VM. 
- *GitHub*: https://github.com/ReactiveX/RxJava
- *Official website*: http://reactivex.io/

## What the sample could do

RxJava is yuuuge but the sample should be kept small.

It could contain:
- a demonstration of how to do an Observable.create() from a fake Websocket stream
- a demonstration of simple operators .map(), .flatmap(), .filter()
- a subscription that prints to the console
- demonstration of interoperability with coroutines, convert from observable to flow and from flow to observable

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by mrclsu** [comment]
I'd like to work on this.

**Comment by jmfayard** [comment]
Cool, it's assigned to you Marcel!

**Comment by LouisCAD** [comment]
@mrclsu Can you confirm you'll use RxJava3?

**Comment by mrclsu** [comment]
Yep, I'll be using RxJava3.

**Comment by jmfayard** [comment]
Marcel, do you still want to contribute an RxJava sample? @mrclsu

**Comment by lprakashv** [comment]
Let me know if this is still up for grabs. I would like to work on it.

**Comment by Bekz7** [comment]
It's still available? I'll be happy to start playing with it.

**Comment by jmfayard** [comment]
@Bekz7 yes it's available, go on!
