### ISSUE TITLE
Sample wanted for skrapeit/skrape.it

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#42]
## About the library

- *Description*:  A Kotlin-based HTML / XML deserialization library that places particular emphasis on ease of use and a high level of readability by providing an intuitive DSL.
- *GitHub*: https://github.com/skrapeit/skrape.it
- *Official website*: https://docs.skrape.it/docs/

## What the sample could do

Parse an HTML file and verify that we can find a given information in it

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by virtuoushub** [comment]
👋 I would like to work on this issue.

Any preference on what HTML file is parsed?

**Comment by jmfayard** [comment]
Cool, thanks!

HTML parsed: maybe the example from Kotlinx.html?
But I'm open to whatever makes sense
