### ISSUE TITLE
Sample wanted for cbeust/klaxon

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#43]
## About the library

- *Description*:  A JSON parser for Kotlin 
- *GitHub*: https://github.com/cbeust/klaxon

## What the sample could do

See sample Moshi and KotlinxSerialization

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by oppongjr** [comment]
@jmfayard please assign this issue to me

**Comment by jmfayard** [comment]
@oppongjr done Isaac :)
Sorry for the other issue

**Comment by oppongjr** [comment]
@jmfayard No problem! I just have to be faster with this one lol.
