### ISSUE TITLE
Sample wanted for sksamuel/hoplite

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#44]
## About the library

- *Description*: A boilerplate-free library for loading configuration files as data classes in Kotlin 
- *GitHub*: https://github.com/sksamuel/hoplite

## What the sample could do

Show how the configuration can be read in a Json, Hocon or Java Properties format
Show how the library works with cascading config files
Show the beautiful errors from the library when a configuration is missing

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by dustinsand** [comment]
I would like to work on this issue.

**Comment by jmfayard** [comment]
Done!
