### ISSUE TITLE
Sample wanted for uchuhimo/konf

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#45]
## About the library

- *Description*:    A type-safe cascading configuration library for Kotlin/Java, supporting most configuration formats 
- *GitHub*: https://github.com/uchuhimo/konf

## What the sample could do

Same as hoplite https://github.com/LouisCAD/kotlin-libraries-playground/issues/44

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by starsep** [comment]
I would like to work on this issue.
Should I create example configurations as files or create them in-memory?

**Comment by jmfayard** [comment]
Cool, thanks @starsep !
I would create configuration files and put them in `src/main/resources`
