### ISSUE TITLE
Sample wanted for  Kotlin/kotlinx.collections.immutable 

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#5]
## About the library

- *Description*:    Immutable persistent collections for Kotlin 
- *GitHub*: https://github.com/Kotlin/kotlinx.collections.immutable
- *Official website*: https://github.com/Kotlin/kotlinx.collections.immutable

## What the sample could do

Left to the imagination of the reader :)

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by lpicanco** [comment]
@jmfayard Can I get this one?

**Comment by jmfayard** [comment]
Yes, go for it!
