### ISSUE TITLE
Sample wanted for Tinder/StateMachine

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#55]
## About the library

- *Description*:    A Kotlin DSL for finite state machine 
- *GitHub*: https://github.com/Tinder/StateMachine

## What the sample could do

A state machine for making a cup of coffee, or something like that

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by OscarSequeiros** [comment]
Hi! I would like to take this. 😉

**Comment by jmfayard** [comment]
Assigned to you :)

**Comment by jmfayard** [comment]
Done in https://github.com/LouisCAD/kotlin-libraries-playground/pull/67
