### ISSUE TITLE
Sample wanted for kotlin-stdlib/kotlin.collections

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#57]
## About the library

- *Description*:   Collection types, such as Iterable, Collection, List, Set, Map and related top-level and extension functions.
- *Official website*: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/

## What the sample could do

As a user coming from Java, 
I use loops `for` `while`, ... everywhere
and I would like to see what's the loop-less alternative
with the most useful functions of `kotlin-stdlib/kotlin.collections`

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by kswadi** [comment]
@jmfayard Can I work on this issue ?

**Comment by jmfayard** [comment]
@kswadi Yes!
To elaborate, what I had in mind for this ticket is something like this:

```kotlin
fun createLists() {
   val squares  = List(10) { it * it } 
   
   val imperativeSquares = mutableListOf<Int>()
   for (int i = 0 ; i < 10 ; i++) {
     imperativeSquares.add(i * i)
   }
   squares shouldBe imperativeSquares
}
```

**Comment by kswadi** [comment]
@jmfayard Thanks for elaborating the problem statement.
