### ISSUE TITLE
Sample wanted for cashapp/contour

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#60]
## About the library

- *Description*:    Layouts with lambdas 😎 
- *GitHub*: https://github.com/cashapp/contour

## What the sample could do

XML had a good ride but times have changed and we should too. 

Demo how you can write the equivalent of a ConstraintLayout but in pure Kotlin

## Wants to contribute the sample?

This issue is blocked by [ Kickstart a project kotlin-android #50 ](https://github.com/LouisCAD/kotlin-libraries-playground/issues/50)

But it can already be assigned to if you feel like working on this library once we the `kotlin-android` project is started. 

So if you are interested, say so in a comment here!

**Comment by priyanka0906** [comment]
@jmfayard  I would like to work on this. May I work on this.

**Comment by LouisCAD** [comment]
@priyanka0906 You've been assigned! 🙂

**Comment by priyanka0906** [comment]
@LouisCAD Thankyou.

**Comment by priyanka0906** [comment]
@LouisCAD I have to wait for #50 to be complete first?

**Comment by jmfayard** [comment]
@priyanka0906 unfortunately nobody is working on #50 currently, Louis and I are busy on other open-source projects.
If you feel you can kickstart an Android project inside this repo, that would be awesome.
Ideally the first screen would be a RecyclerView where each item would lead to a screen featuring one library in isolation.
So for a start, the RecyclerView would have one element: "contour"

**Comment by priyanka0906** [comment]
@jmfayard okay.

**Comment by priyanka0906** [comment]
@jmfayard @LouisCAD  Do I have to make a new package to start an android project or I have to to it in any existing package?
 Please provide guidance I am bit confused in the packages present in the project😅
And a demo should show only a constraint layout so any simple demo would serve the purpose , would you suggest like what kind of demo is required. The one which is shown  here  https://github.com/cashapp/contour  sometime like that ?
Thank you.

**Comment by jmfayard** [comment]
@priyanka0906 you can't use the existing module `kotlin-jvm`, it's JVM only!
You have to create a new Gradle module `kotlin-android` and configure there the Android Gradle Plugin, etc... 
As for the package name, you can use `playground`

**Comment by priyanka0906** [comment]
> @priyanka0906 you can't use the existing module `kotlin-jvm`, it's JVM only!
> You have to create a new Gradle module `kotlin-android` and configure there the Android Gradle Plugin, etc...
> As for the package name, you can use `playground`
> 
> > The one which is shown here https://github.com/cashapp/contour sometime like that ?
> 
> yes

Thank you @jmfayard 🙂

**Comment by priyanka0906** [comment]
@jmfayard I have tried this, please have a look and suggest changes if I doing right or not. I have created a separate repo for now .
https://github.com/priyanka0906/SampleContour 

![Screenshot_1621784990](https://user-images.githubusercontent.com/56197993/119267690-53b68780-bc0d-11eb-99c4-be27a93e8739.png)

**Comment by jmfayard** [comment]
Thanks a lot for your work @priyanka0906 
The Contour code looks good.
What I would like to add is that the first screen should be a RecyclerView - or equivalent - with currently only one item "Contour", who would open your Contour screen.
This way, when someone else wants to make a demo of an Android library, she simply has to add an element in the list that would open her screen

**Comment by priyanka0906** [comment]
@jmfayard yes I will implement recycler View once I will add this code in this repo, I am first trying Contour in a separate app😅.
Thanks for reviewing :)

**Comment by priyanka0906** [comment]
@jmfayard I am struggling with adding `kotlin-android` module .would you please guide me how to add this or share some resources so that I can implement that , I have searched but did not find any satisfactory answer. 
Thank you.

**Comment by jmfayard** [comment]
Hello @priyanka0906 
I have integrated Sample Contour in the project
It's in the `android` branch
I let you work from here
https://github.com/LouisCAD/kotlin-libraries-playground/compare/android?expand=1

**Comment by priyanka0906** [comment]
@jmfayard Thanks a lot 😀
