### ISSUE TITLE
Sample wanted for kotlin-stdlib/kotlin.io

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#61]
## About the library

- *Description*:   IO API for working with files and streams in the Kotlin Standard Library
- *Official website*: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/

## What the sample could do

The stdlib has really useful little things to work with the filesystem, not sure everyone is aware of them.

Show how to use FileTreeWalk, `File.readText()`, `File.writeText()`, File.appendText()`, `File.lines()`, `File.useLines()`, `File.rootName`, ...

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by JohanneA** [comment]
I can do this one

**Comment by jmfayard** [comment]
The issue is all yours, thanks Johanne!

**Comment by jmfayard** [comment]
Done!
