### ISSUE TITLE
Sample wanted forkittinunf / fuel

### ISSUE THREAD

**Issue by vinigmoraes** [LouisCAD/kotlin-libraries-playground#75]
## About the library

- *Description*:   HTTP networking library for Kotlin/Android
- *GitHub*: https://github.com/kittinunf/fuel
- *Official website*: https://fuel.gitbook.io/documentation/

## What the sample could do

HTTP request like POST, GET, PUT and all others verbs 

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by vinigmoraes** [comment]
@jmfayard Can I work on this issue ?

**Comment by jmfayard** [comment]
@vinigmoraes 
Sure!
Look at the samples `ktor-client` and `retrofit` for inspiration

**Comment by jmfayard** [comment]
@vinigmoraes do you still want to contribute a sample for fuel?

**Comment by vinigmoraes** [comment]
@jmfayard Hey, I already opened the PR, but I don`t know why it's broken in github actions, could u help me ?

**Comment by jmfayard** [comment]
It was my fault, don't worry about it

**Comment by jmfayard** [comment]
Simply pull my changes
