### ISSUE TITLE
Sample wanted for kotest/kotest (assertions only)

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#81]
## About the library

- *Description*:    Powerful, elegant and flexible test framework for Kotlin 
- *GitHub*: https://github.com/kotest/kotest/
- *Official website*: https://kotest.io/

## What the sample could do

For kotest, we have good examples of the different testing style from kotest ( `StringSpec`, `FreeSpec`, ...)
But we don't have good examples of matchers.

Show case the assertions from kotest much better that we currently do.

Takee inspiration from [testing.asserts.KluentTests](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/kotlin-testing/src/test/kotlin/testing/asserts/KluentTests.kt)

It would be nice to have examples of:

- Core Matchers
- Arrow Matchers
- Json Matchers
- Clues

<img width="712" alt="Assertions_-_Kotest_Test_Framework" src="https://user-images.githubusercontent.com/459464/96985935-3c9da300-1521-11eb-838a-5d130295509e.png">

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by JohanneA** [comment]
I can do this one if that's okay? 😄

**Comment by LouisCAD** [comment]
Yes it is, you've been assigned! 😃
