### ISSUE TITLE
Sample wanted for google/dagger

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#9]
## About the library

- *Description*:    A fast dependency injector for Android and Java. 
- *GitHub*: https://github.com/google/dagger
- *Official website*: https://dagger.dev/

## What the sample could do

Definitely **not** the meaningless example of the fancy coffee machine with a thermosiphon.

See the [Kodein-DI sample](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/kotlin-jvm/src/main/kotlin/playground/KodeinDI.kt)

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by douglascamata** [comment]
Aaaand I can follow up with this one 🗡️

**Comment by LouisCAD** [comment]
@jmfayard I was thinking it would be great to a have an independent module for kapt dependent libraries so the build time is not too badly impacted when people want to try other stuff.

**Comment by jmfayard** [comment]
@LouisCAD I've tought about that too, but the build time is not an issue for now
`kapt` takes 3 seconds, and the whole executiong 15s
https://scans.gradle.com/s/da5pqt3rwl3ki/performance/build

**Comment by LouisCAD** [comment]
@jmfayard 3 seconds out of 15 is one fifth: significant… but actually, you didn't count it all. Most of the build time is caused by kapt.

So let's address this problem before merging.

![Screenshot_20201003-195209.png](https://user-images.githubusercontent.com/6975237/94998465-39fafe00-05b2-11eb-928d-1c7a219578e7.png)
