### ISSUE TITLE
Sample wanted for jdbi

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/kotlin-libraries-playground#90]
## About the library

- *Description*:   Jdbi provides convenient, idiomatic access to relational data in Java.
- *Official website*: https://jdbi.org/#_introduction_to_jdbi
- For Kotlin: https://jdbi.org/#_kotlin

## What the sample could do

Same as the Exposed or SqlDelight samples, using a H2 in-memory database "jdbc:h2:mem:test"

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by vvkpd** [comment]
I would like to work on this card, could you please assign to me?
Thanks!!!!!

**Comment by jmfayard** [comment]
Done, thanks @vvkpd

**Comment by lprakashv** [comment]
Hi, is this under progress or still up for grabs?

**Comment by jmfayard** [comment]
Feel free to take it up!

**Comment by VadimKulikov** [comment]
I would like to work on it, if possible. Thanks!
